#define NUMBER_OF_TYPES		10
#define UINT8_TYPE 			0
#define UINT16_TYPE 		1
#define UINT32_TYPE			2
#define UINT64_TYPE 		3
#define INT8_TYPE 			4
#define INT16_TYPE 			5
#define INT32_TYPE 			6
#define INT64_TYPE 			7
#define FLOAT_TYPE 			8
#define DOUBLE_TYPE 		9

#define WRITE_PERMISSION 	0b01
#define READ_PERMISSION 	0b10
#define ALL_PERMISSIONS		WRITE_PERMISSION|READ_PERMISSION
