#include "Configurations/SensorsConfiguration.h"
#include "Configurations/CommunicationConfiguration.h"
#include "Definitions/CommunicationDefinition.h"

///////////////////
// Publisher IDs //
///////////////////
#define PUBLISHER_VOLTAGES 		VOLTAGES
#define PUBLISHER_PRESSURES 	PRESSURE_SENSORS
#define PUBLISHER_BATTERY 		BATTERY
#define PUBLISHER_MOTOR		 	MOTOR
#define PUBLISHER_CONTROLLER 	4
#define PUBLISHER_SERVOMOTORS 	5

/////////////////////////////////
// DEFAULT INTERFACE PUBLISHER //
/////////////////////////////////
#define PUBLISHER_VOLTAGES_INTERFACE		UART_EXTENSION
#define PUBLISHER_PRESSURES_INTERFACE		UART_EXTENSION
#define PUBLISHER_BATTERY_INTERFACE			UART_EXTENSION
#define PUBLISHER_MOTOR_INTERFACE			CANFD1
#define PUBLISHER_CONTROLLER_INTERFACE		UART_EXTENSION
#define PUBLISHER_SERVOMOTORS_INTERFACE		UART_EXTENSION

/////////////////////////////
// DEFAULT PUBLISH ADDRESS //
/////////////////////////////
#define PUBLISHER_VOLTAGES_ADDRESS			ALL
#define PUBLISHER_PRESSURES_ADDRESS			ALL
#define PUBLISHER_BATTERY_ADDRESS			ALL
#define PUBLISHER_MOTOR_ADDRESS				ALL
#define PUBLISHER_CONTROLLER_ADDRESS		ALL
#define PUBLISHER_SERVOMOTORS_ADDRESS		ALL

//////////////////////////
// PUBLISHER PRESCALERs //
//////////////////////////
#define PUBLISHER_VOLTAGES_PRESCALER		1
#define PUBLISHER_PRESSURES_PRESCALER		1
#define PUBLISHER_BATTERY_PRESCALER			1
#define PUBLISHER_MOTOR_PRESCALER			1
#define PUBLISHER_CONTROLLER_PRESCALER		1
#define PUBLISHER_SERVOMOTORS_PRESCALER		1

////////////////////////////////
// DEFAULT ACTIVED PUBLISHERS //
////////////////////////////////
//#define PUBLISHER_VOLTAGES_ACTIVE
//#define PUBLISHER_PRESSURES_ACTIVE
//#define PUBLISHER_BATTERY_ACTIVE
#define PUBLISHER_MOTOR_ACTIVE
//#define PUBLISHER_CONTROLLER_ACTIVE
//#define PUBLISHER_SERVOMOTORS_ACTIVE

////////////////////////////
// DEFAULT ACTIVED TOPICs //
////////////////////////////
// PUBLISHER_VOLTAGES
#define PUBLISH_VOLTAGES_TIMEBASE
//#define PUBLISH_VOLTAGES_3_3V
//#define PUBLISH_VOLTAGES_5V

// PUBLISHER_PRESSURES
#define PUBLISH_PRESSURES_TIMEBASE
//#define PUBLISH_PRESSURES_P1_RAW
//#define PUBLISH_PRESSURES_P2_RAW
//#define PUBLISH_PRESSURES_T1_RAW
//#define PUBLISH_PRESSURES_T2_RAW
//#define PUBLISH_PRESSURES_P1
//#define PUBLISH_PRESSURES_P2
//#define PUBLISH_PRESSURES_T1
//#define PUBLISH_PRESSURES_T2

// PUBLISHER_BATTERY
#define PUBLISH_BATTERY_TIMEBASE
//#define PUBLISH_BATTERY_CELL1_RAW
//#define PUBLISH_BATTERY_CELL2_RAW
//#define PUBLISH_BATTERY_IBAT_RAW
//#define PUBLISH_BATTERY_VCELL1
//#define PUBLISH_BATTERY_VCELL2
//#define PUBLISH_BATTERY_VBAT
//#define PUBLISH_BATTERY_IBAT
//#define PUBLISH_BATTERY_TBAT

// PUBLISHER_MOTOR
#define PUBLISH_MOTOR_TIMEBASE
//#define PUBLISH_MOTOR_VOLTAGE_RAW
//#define PUBLISH_MOTOR_CURRENT_RAW
//#define PUBLISH_MOTOR_POWER_RAW
//#define PUBLISH_MOTOR_ENERGY_RAW
//#define PUBLISH_MOTOR_TEMPERATURE_RAW
//#define PUBLISH_MOTOR_VOLTAGE
//#define PUBLISH_MOTOR_CURRENT
#define PUBLISH_MOTOR_POWER
//#define PUBLISH_MOTOR_ENERGY_DOUBLE
#define PUBLISH_MOTOR_ENERGY_FLOAT
//#define PUBLISH_MOTOR_TEMPERATURE

// PUBLISHER_CONTROLLER
#define PUBLISH_CONTROLLER_TIMEBASE
//#define PUBLISH_CONTROLLER_ENCODER
//#define PUBLISH_CONTROLLER_VOLTAGE
//#define PUBLISH_CONTROLLER_CURRENT
//#define PUBLISH_CONTROLLER_POWER
//#define PUBLISH_CONTROLLER_SETPOINT

// PUBLISHER_SERVOMOTORS
#define PUBLISH_SERVOMOTORS_TIMEBASE
//#define PUBLISH_SERVOMOTORS_SETPOINTS
